# TENSORFLOW


In [1]:
#Tensorflow
import tensorflow as tf
import numpy as np

In [2]:
a = tf.constant(15)
b = tf.constant(20)
print (a * b)

tf.Tensor(300, shape=(), dtype=int32)


In [3]:
x = np.random.rand(100).astype(np.float32)
print(x)

[0.12799385 0.58096606 0.29910296 0.00694142 0.25975925 0.3797486
 0.88961273 0.3310374  0.27775624 0.08496003 0.30289632 0.2410771
 0.67625755 0.29335392 0.4855641  0.27671364 0.07724655 0.8408807
 0.54611516 0.16850282 0.93311226 0.59902346 0.07744054 0.8645418
 0.27136397 0.25943798 0.36968452 0.7740288  0.60779756 0.48321673
 0.5668571  0.5143669  0.7270409  0.50491107 0.18207696 0.4124021
 0.34198672 0.06385335 0.4430385  0.61945593 0.2604978  0.21934488
 0.73537314 0.87080723 0.8518073  0.90280056 0.6560933  0.9206784
 0.7176987  0.54321325 0.869632   0.9773521  0.6779225  0.02756881
 0.84069115 0.7712526  0.9160009  0.6589135  0.79401547 0.57787335
 0.437961   0.3654921  0.89207417 0.3965739  0.10891833 0.1754016
 0.56681    0.79024905 0.7615919  0.6460896  0.8629644  0.5368045
 0.02858583 0.6759295  0.8057836  0.9487048  0.9516468  0.64927495
 0.6006711  0.9732554  0.8215058  0.73388505 0.14525354 0.49199668
 0.08263362 0.6758544  0.6199505  0.08212477 0.50432634 0.74270195
 0.

In [4]:
# Define linear equation
y = 0.2 * x + 0.2
# init W
W = tf.Variable(tf.random.normal([1]))
#init b
b = tf.Variable(tf.zeros([1]))

In [16]:
tf.config.run_functions_eagerly(False)  # Enables Graph Execution (default in TF2.x)

In [17]:
# define mse_losss
@tf.function
def mse_loss():
  y_pred = W * x + b
  loss = tf.reduce_mean(tf.square(y_pred-y))
  return loss

In [18]:
optimizer = tf.optimizers.Adam()

In [20]:
# training loop
for step in range(5000):
    with tf.GradientTape() as tape: # Create a GradientTape to track computations
      loss = mse_loss()  # Calculate the loss within the tape's context
      gradients = tape.gradient(loss, [W, b]) # Compute gradients of loss w.r.t. W and b
    optimizer.apply_gradients(zip(gradients, [W, b])) # Apply gradients to update W and b
    if step % 500 == 0:
      print(step, W.numpy(), b.numpy())

0 [0.19999892] [0.19999775]
500 [0.20000003] [0.2]
1000 [0.20006542] [0.2000655]
1500 [0.2000018] [0.20000179]
2000 [0.19999996] [0.19999996]
2500 [0.20000002] [0.19999999]
3000 [0.20001942] [0.2000194]
3500 [0.19999595] [0.19999596]
4000 [0.20000006] [0.20000005]
4500 [0.19993986] [0.19993983]


# PYTORCH

In [21]:
# PYTORCH
import torch
import numpy as np

In [22]:
# create torch tensor
data = [
    [1,2],
    [3,4]
]

x_data = torch.tensor(data)
print(x_data)
print(type(x_data))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [25]:
# convert to np array
x_np = np.array(data)
print(x_np)
print(type(x_np))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [24]:
# convert back to tensor
x_tensor = torch.from_numpy(x_np)
print(x_tensor)
print(type(x_tensor))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [26]:
# create ones tensor
x_ones = torch.ones_like(x_data)
print(x_ones)
print(type(x_ones))

tensor([[1, 1],
        [1, 1]])
<class 'torch.Tensor'>


In [28]:
x_rand = torch.rand_like(x_data, dtype= torch.float)
print(x_rand)
print(type(x_rand))

tensor([[0.4697, 0.9946],
        [0.0445, 0.3389]])
<class 'torch.Tensor'>


In [30]:
shape = (2,3)
rand_t = torch.rand(shape)
print(rand_t)

tensor([[0.2810, 0.8948, 0.4376],
        [0.4248, 0.0932, 0.0022]])


In [31]:
one_t = torch.ones(shape)
print(one_t)
zero_t = torch.zeros(shape)
print(zero_t)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [37]:
# random tensor and properties
random_tensor = torch.rand(3,4)
print(random_tensor)
random_tensor.dtype

tensor([[0.2707, 0.1179, 0.6863, 0.3819],
        [0.0594, 0.9659, 0.0733, 0.9214],
        [0.3209, 0.2332, 0.4530, 0.4776]])


torch.float32

In [38]:
random_tensor.device

device(type='cpu')

In [39]:
random_tensor.shape

torch.Size([3, 4])

In [42]:
# Move to GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print("Tensor is stored in device: \n", tensor.device)
else:
  print("Nahi hai CUDA\n")

Nahi hai CUDA



In [43]:
# 4*4 ones
tensor1 = torch.ones(4,4)
print(tensor1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [44]:
# 4*4 zeros
tensor2 = torch.zeros(4,4)
print(tensor2)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [46]:
#concat
t_concat = torch.cat([tensor1,tensor2])
print(t_concat)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [56]:
# element wise multiply, transpose
t=tensor1.mul(tensor2)
print(t)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [53]:
#transpose
t_concat.T

tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])

In [59]:
n = t.numpy()
print(n)
print(type(n))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
